//
//  AndroidSurfaceHost.swift
//  NucleantApplication
//
#if os(Android)
import Foundation

/// Receives the app's render surface and input from the Android bootstrap.
///
/// The bootstrap (`libNucleantMain.so`, generated by ksproject) owns the JNI
/// edge: the Activity's SurfaceView hands it an `android.view.Surface`, it
/// turns that into an `ANativeWindow *`, and then looks up the `@_cdecl`
/// symbols below with `dlsym(RTLD_DEFAULT, …)`. The two libraries are built by
/// separate toolchain invocations with no link-time relationship, so a C ABI
/// is the only thing that can cross — no Swift type could.
///
/// Direction matters: the bootstrap is loaded first (`System.loadLibrary`,
/// before Python starts) and this library arrives later, inside `_nucleant.so`
/// when Python imports it. So the bootstrap looks *up*, lazily, and these
/// symbols simply have to exist by the time a callback fires.
public enum AndroidSurfaceHost {

    /// The live surface, or nil between destroy and the next create (app
    /// backgrounded, device rotated).
    ///
    /// Written from the UI thread and read from the render thread, so every
    /// access takes the lock — a torn read is a use-after-free of a window the
    /// system has already reclaimed.
    public nonisolated(unsafe) private(set) static var window: OpaquePointer?
    /// Surface size in physical pixels. Android is always fullscreen, so this
    /// *is* the window size rather than a request — the counterpart of iOS
    /// building its UIWindow from the scene.
    public nonisolated(unsafe) private(set) static var width: Int = 0
    public nonisolated(unsafe) private(set) static var height: Int = 0

    private static let lock = NSLock()

    /// Called when a surface becomes available, and again after every
    /// rotation/resize. Set by the platform window so it can build or rebuild
    /// its engine; the bootstrap never calls it directly.
    public nonisolated(unsafe) static var onSurfaceChanged: ((OpaquePointer?, Int, Int) -> Void)?
    /// Called before the surface goes away. Must not return until the renderer
    /// has stopped touching the window — the Surface is only guaranteed valid
    /// until then.
    public nonisolated(unsafe) static var onSurfaceDestroyed: (() -> Void)?

    /// Input, forwarded to whichever window is on screen.
    public nonisolated(unsafe) static var onTouch: ((TouchPhase, Int, Double, Double) -> Void)?
    public nonisolated(unsafe) static var onKey: ((Bool, Int, Int) -> Void)?
    public nonisolated(unsafe) static var onActiveChanged: ((Bool) -> Void)?

    public enum TouchPhase: Int32 {
        case down = 0, moved = 1, up = 2, cancelled = 3
    }

    static func setSurface(_ w: OpaquePointer?, _ width: Int, _ height: Int) {
        lock.lock()
        Self.window = w
        Self.width = width
        Self.height = height
        lock.unlock()
    }

    static func currentSurface() -> (OpaquePointer?, Int, Int) {
        lock.lock()
        defer { lock.unlock() }
        return (window, width, height)
    }
}

// MARK: - C ABI exported to the bootstrap
//
// Names and signatures are the contract documented in the generated
// AndroidSurface.swift; changing one means changing both.

@_cdecl("nucleant_android_surface_created")
public func nucleant_android_surface_created(_ window: OpaquePointer?, _ w: Int32, _ h: Int32) {
    AndroidSurfaceHost.setSurface(window, Int(w), Int(h))
    AndroidSurfaceHost.onSurfaceChanged?(window, Int(w), Int(h))
}

@_cdecl("nucleant_android_surface_resized")
public func nucleant_android_surface_resized(_ w: Int32, _ h: Int32) {
    let (window, _, _) = AndroidSurfaceHost.currentSurface()
    AndroidSurfaceHost.setSurface(window, Int(w), Int(h))
    AndroidSurfaceHost.onSurfaceChanged?(window, Int(w), Int(h))
}

@_cdecl("nucleant_android_surface_destroyed")
public func nucleant_android_surface_destroyed() {
    AndroidSurfaceHost.onSurfaceDestroyed?()
    AndroidSurfaceHost.setSurface(nil, 0, 0)
}

@_cdecl("nucleant_android_touch")
public func nucleant_android_touch(_ phase: Int32, _ pointerId: Int32, _ x: Float, _ y: Float) {
    guard let p = AndroidSurfaceHost.TouchPhase(rawValue: phase) else { return }
    AndroidSurfaceHost.onTouch?(p, Int(pointerId), Double(x), Double(y))
}

@_cdecl("nucleant_android_key")
public func nucleant_android_key(_ down: Int32, _ keyCode: Int32, _ unicodeChar: Int32) {
    AndroidSurfaceHost.onKey?(down != 0, Int(keyCode), Int(unicodeChar))
}

@_cdecl("nucleant_android_active")
public func nucleant_android_active(_ active: Int32) {
    AndroidSurfaceHost.onActiveChanged?(active != 0)
}
#endif
