//
//  AndroidSurfaceHost.swift
//  NucleantApplication
//
#if os(Android)
import Foundation
import Android  // dlsym/dlfcn — Foundation does not re-export it on Android

/// Receives the app's render surface and input from the Android bootstrap.
///
/// The bootstrap (`libNucleantMain.so`, generated by ksproject) owns the JNI
/// edge: the Activity's SurfaceView hands it an `android.view.Surface`, it
/// turns that into an `ANativeWindow *`, and then looks up the `@_cdecl`
/// symbols below with `dlsym(RTLD_DEFAULT, …)`. The two libraries are built by
/// separate toolchain invocations with no link-time relationship, so a C ABI
/// is the only thing that can cross — no Swift type could.
///
/// Direction matters: the bootstrap is loaded first (`System.loadLibrary`,
/// before Python starts) and this library arrives later, inside `_nucleant.so`
/// when Python imports it. So the bootstrap looks *up*, lazily, and these
/// symbols simply have to exist by the time a callback fires.
public enum AndroidSurfaceHost {

    /// The live surface, or nil between destroy and the next create (app
    /// backgrounded, device rotated).
    ///
    /// Written from the UI thread and read from the render thread, so every
    /// access takes the lock — a torn read is a use-after-free of a window the
    /// system has already reclaimed.
    public nonisolated(unsafe) private(set) static var window: OpaquePointer?
    /// Surface size in physical pixels. Android is always fullscreen, so this
    /// *is* the window size rather than a request — the counterpart of iOS
    /// building its UIWindow from the scene.
    public nonisolated(unsafe) private(set) static var width: Int = 0
    public nonisolated(unsafe) private(set) static var height: Int = 0

    private static let lock = NSLock()

    /// Called when a surface becomes available, and again after every
    /// rotation/resize. Set by the platform window so it can build or rebuild
    /// its engine; the bootstrap never calls it directly.
    public nonisolated(unsafe) static var onSurfaceChanged: ((OpaquePointer?, Int, Int) -> Void)?
    /// Called before the surface goes away. Must not return until the renderer
    /// has stopped touching the window — the Surface is only guaranteed valid
    /// until then.
    public nonisolated(unsafe) static var onSurfaceDestroyed: (() -> Void)?

    /// Input, forwarded to whichever window is on screen.
    public nonisolated(unsafe) static var onTouch: ((TouchPhase, Int, Double, Double) -> Void)?
    public nonisolated(unsafe) static var onKey: ((Bool, Int, Int) -> Void)?
    public nonisolated(unsafe) static var onActiveChanged: ((Bool) -> Void)?

    public enum TouchPhase: Int32 {
        case down = 0, moved = 1, up = 2, cancelled = 3
    }

    static func setSurface(_ w: OpaquePointer?, _ width: Int, _ height: Int) {
        lock.lock()
        Self.window = w
        Self.width = width
        Self.height = height
        lock.unlock()
    }

    static func currentSurface() -> (OpaquePointer?, Int, Int) {
        lock.lock()
        defer { lock.unlock() }
        return (window, width, height)
    }

    /// Asks the bootstrap to re-dispatch the surface it already has.
    ///
    /// The direction described above has a gap: the bootstrap looks these
    /// symbols up lazily *and caches the miss*, so every surface event that
    /// fires before `_nucleant.so` loads is dropped for good. That is the
    /// normal case, not an edge one — the Activity's surface is created while
    /// assets are still unpacking, tens of seconds before Python starts, and
    /// there is no second event to recover on. `window` then stays nil and the
    /// first `present()` finds nothing to draw into.
    ///
    /// The bootstrap exports `nucleant_refresh_host_hooks` to close it: it
    /// clears the cached misses and replays the live surface through
    /// `nucleant_android_surface_created`. Reached by dlsym for the same reason
    /// the hooks above are — the two libraries share no link-time relationship,
    /// only the C ABI.
    ///
    /// Idempotent and cheap; a miss means the bootstrap predates the symbol, in
    /// which case behaviour is exactly what it was before.
    static func replayFromBootstrap() {
        guard replayOnce == false else { return }
        replayOnce = true
        typealias RefreshFn = @convention(c) (UnsafePointer<CChar>?) -> Void
        // RTLD_DEFAULT first, then the bootstrap by name. The fallback is the
        // one that actually fires: RTLD_DEFAULT searches only the global group,
        // and System.loadLibrary puts libNucleantMain.so in the app's
        // classloader namespace without adding it there, so this library — which
        // Python dlopened into its own namespace — cannot see it that way.
        // dlopen on an already-loaded library returns its existing handle rather
        // than mapping a second copy.
        let rtldDefault = UnsafeMutableRawPointer(bitPattern: 0)  // RTLD_DEFAULT
        var sym = dlsym(rtldDefault, "nucleant_refresh_host_hooks")
        if sym == nil, let handle = dlopen("libNucleantMain.so", RTLD_NOW) {
            sym = dlsym(handle, "nucleant_refresh_host_hooks")
        }
        guard let sym else {
            NSLog("[nucleant] bootstrap exports no nucleant_refresh_host_hooks — "
                  + "a surface created before this library loaded stays lost")
            return
        }
        // Hand over this library's own path so the bootstrap can dlopen it for
        // a handle: the barrier is symmetric, and its RTLD_DEFAULT cannot see
        // our @_cdecl hooks any more than ours could see its refresh symbol.
        // dladdr against a symbol in this module reports the file it came from.
        var info = Dl_info()
        let selfAddress = unsafeBitCast(
            nucleant_android_surface_created as @convention(c) (OpaquePointer?, Int32, Int32) -> Void,
            to: UnsafeMutableRawPointer.self
        )
        let path: UnsafePointer<CChar>? =
            dladdr(selfAddress, &info) != 0 ? info.dli_fname : nil
        if path == nil {
            NSLog("[nucleant] dladdr could not name this library — the bootstrap "
                  + "will fall back to RTLD_DEFAULT and keep dropping events")
        }
        unsafeBitCast(sym, to: RefreshFn.self)(path)
    }

    private nonisolated(unsafe) static var replayOnce = false

    /// Tells the bootstrap a frame has reached the surface, so the Activity can
    /// take its presplash down. Reached the same way as `replayFromBootstrap`,
    /// and equally optional: an older bootstrap without the symbol just keeps
    /// its presplash up, which is what it did before this existed.
    static func signalFirstFrame() {
        typealias FirstFrameFn = @convention(c) () -> Void
        let rtldDefault = UnsafeMutableRawPointer(bitPattern: 0)  // RTLD_DEFAULT
        var sym = dlsym(rtldDefault, "nucleant_android_first_frame")
        if sym == nil, let handle = dlopen("libNucleantMain.so", RTLD_NOW) {
            sym = dlsym(handle, "nucleant_android_first_frame")
        }
        guard let sym else { return }
        unsafeBitCast(sym, to: FirstFrameFn.self)()
    }
}

// MARK: - C ABI exported to the bootstrap
//
// Names and signatures are the contract documented in the generated
// AndroidSurface.swift; changing one means changing both.

@_cdecl("nucleant_android_surface_created")
public func nucleant_android_surface_created(_ window: OpaquePointer?, _ w: Int32, _ h: Int32) {
    AndroidSurfaceHost.setSurface(window, Int(w), Int(h))
    AndroidSurfaceHost.onSurfaceChanged?(window, Int(w), Int(h))
}

@_cdecl("nucleant_android_surface_resized")
public func nucleant_android_surface_resized(_ w: Int32, _ h: Int32) {
    let (window, _, _) = AndroidSurfaceHost.currentSurface()
    AndroidSurfaceHost.setSurface(window, Int(w), Int(h))
    AndroidSurfaceHost.onSurfaceChanged?(window, Int(w), Int(h))
}

@_cdecl("nucleant_android_surface_destroyed")
public func nucleant_android_surface_destroyed() {
    AndroidSurfaceHost.onSurfaceDestroyed?()
    AndroidSurfaceHost.setSurface(nil, 0, 0)
}

@_cdecl("nucleant_android_touch")
public func nucleant_android_touch(_ phase: Int32, _ pointerId: Int32, _ x: Float, _ y: Float) {
    guard let p = AndroidSurfaceHost.TouchPhase(rawValue: phase) else { return }
    AndroidSurfaceHost.onTouch?(p, Int(pointerId), Double(x), Double(y))
}

@_cdecl("nucleant_android_key")
public func nucleant_android_key(_ down: Int32, _ keyCode: Int32, _ unicodeChar: Int32) {
    AndroidSurfaceHost.onKey?(down != 0, Int(keyCode), Int(unicodeChar))
}

@_cdecl("nucleant_android_active")
public func nucleant_android_active(_ active: Int32) {
    AndroidSurfaceHost.onActiveChanged?(active != 0)
}
#endif
